### ISSUE TITLE
NullPointer Exception when credential is not set because instance role is used to authenticate to SQS

### ISSUE THREAD

**Issue by coreyjackwilson** [jenkinsci/aws-sqs-trigger-plugin#4]
### Jenkins and plugins versions report

<Details>
Jenkins: 2.401.1
OS: Linux - 5.4.238-148.347.amzn2.x86_64
Java: 11.0.19 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
authentication-tokens:1.53.v1c90fd9191a_b_
aws-credentials:191.vcb_f183ce58b_9
aws-java-sdk:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-cloudformation:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-codebuild:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-ec2:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-ecr:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-ecs:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-efs:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-elasticbeanstalk:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-iam:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-kinesis:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-logs:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-minimal:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-sns:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-sqs:1.12.481-392.v8b_291cfcda_09
aws-java-sdk-ssm:1.12.481-392.v8b_291cfcda_09
aws-secrets-manager-secret-source:1.62.v120c8e5058ee
aws-sqs-trigger:1.2
bootstrap5-api:5.3.0-1
bouncycastle-api:2.28
branch-api:2.1122.v09cb_8ea_8a_724
caffeine-api:3.1.6-115.vb_8b_b_328e59d8
checks-api:2.0.0
cloudbees-folder:6.815.v0dd5a_cb_40e0e
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
configuration-as-code:1647.ve39ca_b_829b_42
credentials:1254.vb_96f366e7b_a_d
credentials-binding:604.vb_64480b_c56ca_
dark-theme:315.va_22e7d692ea_a
display-url-api:2.3.7
durable-task:507.v050055d0cb_dd
echarts-api:5.4.0-5
envinject:2.901.v0038b_6471582
envinject-api:1.199.v3ce31253ed13
font-awesome-api:6.4.0-1
git:5.1.0
git-client:4.4.0
git-parameter:0.9.18
hashicorp-vault-pipeline:1.4
hashicorp-vault-plugin:360.v0a_1c04cf807d
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.2-350.v0c2f3f8fc595
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
job-dsl:1.84
jquery3-api:3.7.0-1
junit:1214.va_2f9db_3e6de0
kubernetes:3937.vd7b_82db_e347b_
kubernetes-client-api:6.4.1-215.v2ed17097a_8e9
kubernetes-credentials:0.10.0
mailer:457.v3f72cb_e015e5
matrix-project:789.v57a_725b_63c79
metrics:4.2.18-439.v86a_20b_a_8318b_
mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
okhttp-api:4.11.0-145.vcb_8de402ef81
pipeline-build-step:496.v2449a_9a_221f2
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:656.va_a_ceeb_6ffb_f7
pipeline-input-step:468.va_5db_051498a_4
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2141.v5402e818a_779
pipeline-model-definition:2.2141.v5402e818a_779
pipeline-model-extensions:2.2141.v5402e818a_779
pipeline-rest-api:2.33
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2141.v5402e818a_779
pipeline-stage-view:2.33
pipeline-utility-steps:2.15.4
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.3.0
role-strategy:633.v836e5b_3e80a_5
saml:4.418.vdfa_7489a_b_a_2d
scm-api:676.v886669a_199a_a_
script-security:1251.vfe552ed55f8d
slack:664.vc9a_90f8b_c24a_
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
ssh-credentials:305.v8f4381501156
sshd:3.249.v2dc2ea_416e33
structs:324.va_f5d6774f3a_d
theme-manager:193.vcef22f6c5f2b_
throttle-concurrents:2.14
token-macro:359.vb_cde11682e0c
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
workflow-aggregator:596.v8c21c963d92d
workflow-api:1219.v05cd837ea_249
workflow-basic-steps:1017.vb_45b_302f0cea_
workflow-cps:3697.vb_470e454c232
workflow-durable-task-step:1247.v7f9dfea_b_4fd0
workflow-job:1316.vd2290d3341a_f
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
</Details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu Kubernetes

### Reproduction steps

1. Setup Jenkins in EKS
2. Have the pod assume a role with the service account that can access the SQS 
3. Setup the trigger, do not set an id for the credential (because you already have auth setup)

### Expected Results

I can poll from SQS with no errors in the log

### Actual Results

Logs get NullPointer exception stating that the credential is not set. 

### Anything else?

Can we add a guard against this so that if the credential isn't set (i.e. because we use the jobs DSL), that it won't complain as it assumes we are relying on the assumed credential?

**Comment by coreyjackwilson** [comment]
Stacktrace
```
SEVERE    h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (sqsPollTask thread/69) died unexpectedly due to an uncaught exception. This may leave your server corrupted and usually indicates a software bug.  │
│ jenkins java.lang.NullPointerException                                                                                                                                                                                                                                              │
│ jenkins     at java.base/java.util.Objects.requireNonNull(Objects.java:221)                                                                                                                                                                                                         │
│ jenkins     at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:58)                                                                                                                                                                                       │
│ jenkins     at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:135)                                                                                                                                                                           │
│ jenkins     at io.jenkins.plugins.sqs.AwsCredentialsHelper.getAWSCredentials(AwsCredentialsHelper.java:22)                                                                                                                                                                          │
│ jenkins     at io.jenkins.plugins.sqs.SqsPollTask.lambda$execute$1(SqsPollTask.java:42)                                                                                                                                                                                             │
│ jenkins     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)                                                                                                                                                                                    │
│ jenkins     at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)                                                                                                                                                                            │
│ jenkins     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)                                                                                                                                                                                      │
│ jenkins     at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)                                                                                                                                                                                       │
│ jenkins     at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)                                                                                                                                                                                      │
│ jenkins     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)                                                                                                                                                                                            │
│ jenkins     at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)                                                                                                                                                                                          │
│ jenkins     at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)                                                                                                                                                                                            │
│ jenkins     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)                                                                                                                                                                                │
│ jenkins     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)                                                                                                                                                                          │
│ jenkins     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)                                                                                                                                                                                      │
│ jenkins     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)                                                                                                                                                                                     │
│ jenkins     at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)                                                                                                                                                                                │
│ jenkins     at io.jenkins.plugins.sqs.SqsPollTask.execute(SqsPollTask.java:40)                                                                                                                                                                                                      │
│ jenkins     at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:102)                                                                                                                                                                                            │
│ jenkins     at java.base/java.lang.Thread.run(Thread.java:829) 
```

**Comment by coreyjackwilson** [comment]
Can we just add a check here?
https://github.com/jenkinsci/aws-sqs-trigger-plugin/blob/eb3a98f05c65f1f6950064fc8162dc131f91f7fe/src/main/java/io/jenkins/plugins/sqs/SqsPollTask.java#L41

Basically change it to something like this
```
String credentialsId = trigger.getSqsTriggerCredentialsId();
if (credentialsId == null || credentialsId.isBlank()) {
    List<Message> messages = sqsPoller.getMessagesAndDelete(trigger.getSqsTriggerQueueUrl(), null);
} else {
    AWSCredentials awsCredentials = AwsCredentialsHelper.getAWSCredentials((credentialsId));
    List<Message> messages = sqsPoller.getMessagesAndDelete(trigger.getSqsTriggerQueueUrl(), awsCredentials);
}                
```

That should prevent the error because the client constructor even anticipates a null and then uses instance level role auth.

**Comment by coreyjackwilson** [comment]
Maybe someone can help with testing here: https://github.com/jenkinsci/aws-sqs-trigger-plugin/pull/5
